### ISSUE TITLE
Rare crashes on big projects because of invalid JSON

### ISSUE THREAD

**Issue by jkrems** [buggerjs/node-inspect#10]
Sometimes when running this against non-trivial apps, it crashes with a parse error while it's trying to parse one of the websocket messages.

**Comment by jkrems** [comment]
Easy repro even on `examples/empty.js`:

```
> ./cli.js examples/empty.js
< Debugger listening on port 9229.
< Warning: This is an experimental feature and could change at any time.
< To start debugging, open the following URL in Chrome:
<     chrome-devtools://devtools/remote/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=localhost:9229/aa357a6a-29b6-4abb-9042-70960d980880
< Debugger attached.
break in examples/empty.js:2
  1 (function (exports, require, module, __filename, __dirname) {
> 2 });
debug> exec console.profile()
undefined
debug> exec console.profileEnd()
There was an internal error in node-inspect. Please report this bug.
Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Client._handleChunk ([path to]/node-inspect/lib/internal/inspect-protocol.js:188:58)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```
